[project]
name = "cim-loader"
version = "0.0.2a0"
description = "CIM Database Uploader & Downloader"
authors = [
    {name = "A. Anderson", email = "19935503+AAndersn@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cim-graph>=0.4.3a1",
]

[project.optional-dependencies]
# Extra dependencies for GridAPPS-D integration
gridappsd = [
    "gridappsd-python",
]
# Development dependencies
dev = [
    "pre-commit>=2.17.0",
    "graphviz>=0.19.1",
    "ipykernel>=6.25.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["cimloader"]